name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    continue-on-error: true

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 14.15.0

      - name: Install packages
        run: yarn install --frozen-lockfile

      - name: Build
        run: yarn build

      - name: Test
        run: yarn test --coverage

      - name: Test web app
        run: yarn workspace @sandbox/web test --coverage

      - name: Start
        run: yarn start
